version: '3'

services:
  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123
      - MSSQL_PID=Developer
    volumes:
      - ./mssqldata:/var/opt/mssql
  timeseries_generator:
    build: .
    links:
      - "mssql"
    volumes:
      - ./dataset:/data
